<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Authors>Jerrod Eiman</Authors>
    <Description>HatTrick Labs command line interface tools.</Description>
    <Company>HatTrick Labs</Company>
    <Copyright>Hat Trick Labs</Copyright>
    <PackageProjectUrl>https://github.com/HatTrickLabs/cli</PackageProjectUrl>
    <PackageIcon>htl-nuget-logo.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryType>https://github.com/HatTrickLabs/cli</RepositoryType>
    <PackageTags>command line cli</PackageTags>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <EnableNETAnalyzers>False</EnableNETAnalyzers>
    <RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\build\htl-nuget-logo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
