<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Authors>Jerrod Eiman</Authors>
    <Description>HatTrick Labs command line interface tools.</Description>
    <Company>HatTrick Labs</Company>
    <Copyright>Hat Trick Labs</Copyright>
    <PackageProjectUrl>https://github.com/HatTrickLabs/cli</PackageProjectUrl>
    <PackageIcon>htl-nuget-logo.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryType>https://github.com/HatTrickLabs/cli</RepositoryType>
    <PackageTags>command line cli</PackageTags>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <EnableNETAnalyzers>False</EnableNETAnalyzers>
    <RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>1.0.19</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Outputs\Templates\command-help.htt" />
    <None Remove="Outputs\Templates\invalid-input-help.htt" />
    <None Remove="Outputs\Templates\namespace-help.htt" />
    <None Remove="Outputs\Templates\namespace-wildcard-help.htt" />
    <None Remove="Outputs\Templates\root-help.htt" />
    <None Remove="Outputs\Templates\usage-help.htt" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Outputs\Templates\command-help.htt" />
    <EmbeddedResource Include="Outputs\Templates\namespace-help.htt" />
    <EmbeddedResource Include="Outputs\Templates\namespace-wildcard-help.htt">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Outputs\Templates\root-help.htt" />
    <EmbeddedResource Include="Outputs\Templates\usage-help.htt" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\build\htl-nuget-logo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HatTrick.Text.Templating" Version="2.2.0" />
  </ItemGroup>

</Project>
